apiVersion: v1
kind: Service
metadata:
  name: salutator-mysql
  labels:
    app: salutator
spec:
  ports:
    - port: 3306
  selector:
    app: salutator
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: salutator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: salutator-mysql
  labels:
    app: salutator
spec:
  selector:
    matchLabels:
      app: salutator
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: salutator
        tier: mysql
    spec:
      containers:
      - image: skel84/salutator-mysql:latest
        name: mysql
        env:
          - name: MYSQL_DATABASE
            value: hello
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      readinessProbe:
        exec:
          command:
          - mysql
          - -hlocalhost
          - -uroot
          - -p$MYSQL_ROOT_PASSWORD
          - hello
          - -e"SELECT * from salutation"
        initialDelaySeconds: 20
      periodSeconds: 5
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

